image: gitpod/workspace-full-vnc
tasks:
  - command: |
      sudo apt-get update
      sudo apt-get install -y firefox
      sleep 20s
      timeout 5 firefox
      MM_FFDIR=(~/.mozilla/firefox/*.default-release)
      cp user.js ${MM_FFDIR}
      ln -f -s ${GITPOD_REPO_ROOTS}/IE6/chrome ${MM_FFDIR}/chrome
ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: open-browser
