image: gitpod/workspace-full-vnc

tasks:
  - command: bash .gitpod/prerun.sh && bash .gitpod/installation.sh

ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    name: VNC Viewer
    onOpen: open-browser
