image: gitpod/workspace-full-vnc
tasks:
  - command: |
      sudo apt-get update
      sudo apt-get install -y firefox
      sleep 20s
      timeout 5 firefox
      MM_FFDIR=(~/.mozilla/firefox/*.default-release)
      ln -f -s ${GITPOD_REPO_ROOTS}/IE6/chrome ${MM_FFDIR}/chrome
      echo "user_pref(\"toolkit.legacyUserProfileCustomizations.stylesheets\", true);" >> ${MM_FFDIR}/user.js
      echo "user_pref(\"browser.compactmode.show\", true);" >> ${MM_FFDIR}/user.js
ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: open-browser
